### ISSUE TITLE
Errors/warnings only detected for files that are in an unsaved state

### ISSUE THREAD

**Issue by cameronhimself** [AtomLinter/linter-flow#78]
Steps to reproduce (for me, anyway):

1. Open a saved file that is known to contain flow errors. Linter displays no errors.
2. Start typing anything. Linter immediately starts displaying all errors.
3. Either undo or manually bring the file back to its saved state and the linter errors disappear again.
4. Start typing again so that the errors once again show up.
5. Save the file. Errors immediately disappear.

Atom, my flow binary, and this plugin are all up to date (1.6.0, 0.22.1, and 5.0.0 respectively). Mac OS X 10.9.5.

**Comment by nmn** [comment]
This is interesting. Looks like the flow cli has changed a little. I'll look into it.

**Comment by cameronhimself** [comment]
So it turns out that this is the behavior I see for a file that _does not_ have the `// @flow` comment at the top. When I add the comment, everything works as expected.

So I guess this issue report is now about how flow is enabled for unsaved files even when the comment tag is not present. My `.flowconfig` file is empty (no changes made to it after `flow init`).

**Comment by nmn** [comment]
This was regression in v5.0.0 where the detection for the `@flow` comment was broken.

`// @flow` is ignored
`/* @flow */` is accepted.

If there is no inline comment in the file, it would incorrectly assume the comment exists.

Fixed in #80

**Comment by nmn** [comment]
Should be fixed in 5.1.0

**Comment by anthillape** [comment]
My colleagues and I are still seeing the behaviour seen in the original issue, with the same steps to reproduce. I tried changing the flow comment, however, none seems to work as expected. I am on 5.1.0, atom 1.7.2 osx 10.11.1, with linter 1.11.4 here is a file that displays this behaviour:

```
// @flow

const foo: number = '';

```

**Comment by Arcanemagus** [comment]
@cameronhimself  or @anthillape are either of you still experiencing this issue with v5.5.0?

**Comment by emiljohnsen** [comment]
I'm experiencing the bug as of right now, with version 5.5.0. I get hints both as tooltip and in the bottom area in an unsaved file, but they are gone as soon as I save the file. 


This issue occurs whether or not I have linter-eslint enabled, which also reports to the same areas. 

I tried it with both` /* @flow */` and `// @flow`

**Comment by nmn** [comment]
This bug is probably a bug with flow itself. Longer-flow uses flow status for saved files. But it uses a different command for unsaved files. That could be causing the problem. Nuclide fixes this problem by only showing you errors after you save the file. Would you prefer that?

**Comment by emiljohnsen** [comment]
I'd prefer linter-flow to behave like linter-eslint, and I'd prefer to use linter-flow instead of dealing with a second "type" of plugin, hah. 

I haven't checked out nuclide, or any other particular flow linters. 

Eslint, IIRC, evaluates the files on save and displays errors afterwards, which I'd prefer.

**Comment by nmn** [comment]
@emiljohnsen aslant works on the fly too. There's an option though. I'll try and make it work with that option.
